name: Front-end-ci-and-Deploy
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: Unit and end-to-end tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies with install
        run: npm install
      - name: Install Dependencies with ci
        run: npm ci
      - name: Install Eslint
        run: npm install -g eslint
      - name: Install Prettier
        run: npm i -g prettier

      - name: Run ESLint
        run: npm run lint
      

      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false

      - name: Unit Tests
        run: npm test -- --watchAll=false  --passWithNoTests


      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          working-directory: ./web-ui

  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    needs: ci
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      

      - name: Creating .env file
        run: |
          echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} >> ./.env
      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false
      - name: Deployment on Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web-ui
  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      

      - name: Creating .env file
        run: |
          echo REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} >> ./.env
      - name: Preparing Build Directory
        run: npm run build
        env:
          CI: false
      - name: Deployment on Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web-ui